### ISSUE TITLE
关于数据集下载的问题

### ISSUE THREAD

**Issue by OkLetsGoi** [weiguangzhao/PBNet#10]
您好，再次打扰您一下，我按照网上的教程，下载出来的目录结构和您readme里面的目录结构不同，请问我这是哪里出现问题了，正确的下载方式应该是什么样子呢？

这是您readme里面的：
![a99d73b1b2cb64d81126e2b30a783fa](https://github.com/weiguangzhao/PBNet/assets/148300443/377381d8-cdce-4662-a2ab-d71b473ed472)

这是网上教程：
![53671cfd157b81346a3abc6782fb746](https://github.com/weiguangzhao/PBNet/assets/148300443/97a4a1f2-5637-4bca-9570-f1b6cee6b33f)

这是我应用后的：
![f1ccd7db4e711319269611b2a2c748c](https://github.com/weiguangzhao/PBNet/assets/148300443/f70994a2-2a11-47ba-962f-84211f9a554e)

**Comment by weiguangzhao** [comment]
是的 你需要编写脚本将文件按照我readme的方式进行排列, 我提供了一个示例脚本PBNet/datasets/scannetv2/split_data.py

**Comment by OkLetsGoi** [comment]
> 是的 你需要编写脚本将文件按照我readme的方式进行排列, 我提供了一个示例脚本PBNet/datasets/scannetv2/split_data.py

好滴感谢！打扰你这么多次，抱歉抱歉~
