### ISSUE TITLE
Problems with setup.py compiled by pb_lib

### ISSUE THREAD

**Issue by 3171228612** [weiguangzhao/PBNet#4]
Hello, when I installed the pb_lib compilation, I reported an error that the cuda version of 11.7 was detected, but the requirement was 10.2. May I ask how it was compiled on the 3090 graphics card

**Comment by weiguangzhao** [comment]
Hi, thanks for your attention. Could you provide the screenshot of that error and the version of nvcc, cudatoolkit and pytorch? By the way, this kind of problem is mostly caused by version compatibility. You can try to install a 10.0 cuda and modify the setup file, or increase the versions of cudatoolkit and pytorch.

**Comment by 3171228612** [comment]
Thank you for your answer. I understand the situation. But my server does compile with cuda version of 11.7, my nvcc is 11.7, and pytorch will report errors regardless of 1.10.0 or later. Below is a screenshot of my error. Please also understand that there is no way to execute the compiled code of 10.2.
![微信截图_20231123160614](https://github.com/weiguangzhao/PBNet/assets/103794255/99408e5e-b330-4078-8593-62f527797f36)
![微信截图_20231123160745](https://github.com/weiguangzhao/PBNet/assets/103794255/9c7ec23c-ff04-4d51-af76-5247f5e1fc82)

**Comment by weiguangzhao** [comment]
Hi, it seems that your Pytorch version does not match. Please check the detail version of your Pytorch by the following command.
`conda activate pbnet`
`conda list -e | grep pytorch`
The detailed version of Pytorch should be the following pic:
![image](https://github.com/weiguangzhao/PBNet/assets/22412975/2a235b35-dbf6-436a-b2fe-eba755cb4908)
You can use the following command to change the pytorch to 11.X cuda:
`conda install -c pytorch pytorch=1.9.0 cudatoolkit=11.1`
By the way, the version of Pytorch higher than 1.10 should also work, the key issue is that its detailed version should be cuda11.X

**Comment by 3171228612** [comment]
It seems that there is something wrong with my server:



Either `conda install -c pytorch pytorch=1.9.0 cudatoolkit=11.1` or` conda install -c pytorch pytorch=1.10.0 cudatoolkit=11.3`

Will report an error saying that the appropriate packages cannot be found
![微信截图_20231123170320](https://github.com/weiguangzhao/PBNet/assets/103794255/a24eac49-108e-498e-ae33-51cda656bbac)

**Comment by weiguangzhao** [comment]
Add the nvidia channel by the following command:
`conda install -c pytorch -c nvidia pytorch=1.9.0 cudatoolkit=11`

**Comment by 3171228612** [comment]
Thanks to the author, this has been successfully resolved, the cause seems to be the -c conda-forge upgrade after the incompatibility caused by the removal, can successfully install torch=1.9.0 and compile.

Thanks again for your guidance. I have also studied in this direction for some time and made some small achievements. map has reached 55.4 network, but it is not completely open source

If you don't mind, I would like to take the liberty of adding your contact information, if you don't think it's any trouble. The following is my E-mail address 3171228612@qq.com
