### ISSUE TITLE
你好，请问网络可以应用在自己的数据集吗

### ISSUE THREAD

**Issue by OkLetsGoi** [weiguangzhao/PBNet#8]
你好，请问网络可以应用在自己的数据集吗？

**Comment by weiguangzhao** [comment]
我们的方法可以应用在其他数据集上 比如盒子 积木 桌面等，我们自己也验证过。 但是输入格式和超参数需要进行微调。

**Comment by OkLetsGoi** [comment]
> 我们的方法可以应用在其他数据集上 比如盒子 积木 桌面等，我们自己也验证过。 但是输入格式和超参数需要进行微调。

我是一名学生，我的方向是树林的单木分割，我想用您的网络来跑自己的数据集，但是我又刚接触这个方向，不太清楚能不能用您的网络来跑树林的点云数据，您要是方便的话可以帮我解答一下吗，谢谢谢谢~

**Comment by weiguangzhao** [comment]
可以用来做树林分割 遇到问题你可以私聊我的邮箱 邮箱地址在论文中有给出

**Comment by OkLetsGoi** [comment]
> 可以用来做树林分割 遇到问题你可以私聊我的邮箱 邮箱地址在论文中有给出

好滴好滴，感谢感谢！！！！祝您学术天天向上，生活开心！！！

**Comment by weiguangzhao** [comment]
共勉！

**Comment by OkLetsGoi** [comment]
> 共勉！

好滴！！
