### ISSUE TITLE
能否使用较小公共数据集作为您readme中的数据准备部分

### ISSUE THREAD

**Issue by OkLetsGoi** [weiguangzhao/PBNet#9]
您自述文件中给出的 ScanNet v2 数据集需要 1.2T 存储空间，您可以发布一个使用较小的数据集作为数据准备部分的自述文件吗，如S3DIS数据集，谢谢谢谢，祝您生活愉快！

**Comment by weiguangzhao** [comment]
你不需要下载完整的ScanNetV2，只需要下载我readme中的几种类型文件(可以在脚本文件中指定下载类型)，大约9G

**Comment by OkLetsGoi** [comment]
> 你不需要下载完整的ScanNetV2，只需要下载我readme中的几种类型文件（可以在文件中下载类型），大约9个G

谢谢谢谢！
